hitting_tips = [
(1, 'Separate the children immediately to ensure safety.', 'hitting', '2024-12-08', 'admin'),
(2, 'Stay calm to model appropriate behavior for your child.', 'hitting', '2024-12-08', 'admin'),
(3, 'Kneel to your child’s level to establish a non-threatening presence.', 'hitting', '2024-12-08', 'admin'),
(4, 'Hold your child gently if needed to prevent further hitting.', 'hitting', '2024-12-08', 'admin'),
(5, 'Acknowledge the other child’s feelings and comfort them.', 'hitting', '2024-12-08', 'admin'),
(6, 'Explain the need to stop hitting without yelling.', 'hitting', '2024-12-08', 'admin'),
(7, 'Use time-outs to give your child space to calm down.', 'hitting', '2024-12-08', 'admin'),
(8, 'Offer alternative physical outlets, like squeezing a stress ball.', 'hitting', '2024-12-08', 'admin'),
(9, 'Role-play scenarios to practice non-violent responses.', 'hitting', '2024-12-08', 'admin'),
(10, 'Set clear and consistent boundaries around physical aggression.', 'hitting', '2024-12-08', 'admin'),
(11, 'Reinforce positive behavior when your child uses words instead of hitting.', 'hitting', '2024-12-08', 'admin'),
(12, 'Monitor playtime for early signs of frustration or anger.', 'hitting', '2024-12-08', 'admin'),
(13, 'Provide structured activities to minimize unregulated play.', 'hitting', '2024-12-08', 'admin'),
(14, 'Use visual aids, like books or videos, to explain the consequences of hitting.', 'hitting', '2024-12-08', 'admin'),
(15, 'Regularly remind your child about acceptable behavior.', 'hitting', '2024-12-08', 'admin'),
(16, 'Introduce a behavior chart to track and reward progress.', 'hitting', '2024-12-08', 'admin'),
(17, 'Involve your child in problem-solving: ask them how they can express frustration differently.', 'hitting', '2024-12-08', 'admin'),
(18, 'Avoid exposing your child to violent media.', 'hitting', '2024-12-08', 'admin'),
(19, 'Teach calming techniques like deep breathing or counting to ten.', 'hitting', '2024-12-08', 'admin'),
(20, 'Limit over-stimulating environments if they seem to trigger aggression.', 'hitting', '2024-12-08', 'admin'),
(21, 'I see you’re upset. Can you tell me what happened?', 'hitting', '2024-12-08', 'admin'),
(22, 'It’s okay to feel angry, but it’s not okay to hit.', 'hitting', '2024-12-08', 'admin'),
(23, 'Hands are for helping, not hurting.', 'hitting', '2024-12-08', 'admin'),
(24, 'How would you feel if someone hit you? Let’s think about that.', 'hitting', '2024-12-08', 'admin'),
(25, 'What else could you do if you feel angry?', 'hitting', '2024-12-08', 'admin'),
(26, 'Can we use words to explain what we need?', 'hitting', '2024-12-08', 'admin'),
(27, 'I’m here to help you solve this problem.', 'hitting', '2024-12-08', 'admin'),
(28, 'I know you’re a kind person; let’s act kindly.', 'hitting', '2024-12-08', 'admin'),
(29, 'Let’s take a deep breath together and talk.', 'hitting', '2024-12-08', 'admin'),
(30, 'You are not in trouble, but we need to talk about hitting.', 'hitting', '2024-12-08', 'admin'),
(31, 'When we hit, it makes others feel hurt. We want to make others feel happy.', 'hitting', '2024-12-08', 'admin'),
(32, 'I know it’s hard, but hitting doesn’t solve the problem.', 'hitting', '2024-12-08', 'admin'),
(33, 'Let’s say sorry to them and try to fix what happened.', 'hitting', '2024-12-08', 'admin'),
(34, 'Can you show me how we use gentle hands?', 'hitting', '2024-12-08', 'admin'),
(35, 'You’re learning to control big feelings, and I’m proud of you.', 'hitting', '2024-12-08', 'admin'),
(36, 'Recognize that hitting is often a child’s way of expressing frustration or unmet needs.', 'hitting', '2024-12-08', 'admin'),
(37, 'Understand that young children might lack the vocabulary to express emotions.', 'hitting', '2024-12-08', 'admin'),
(38, 'Remember that hitting is a developmental phase and can be improved with guidance.', 'hitting', '2024-12-08', 'admin'),
(39, 'Avoid taking the behavior personally—your child isn’t "bad."', 'hitting', '2024-12-08', 'admin'),
(40, 'Reflect on potential triggers: hunger, tiredness, or overstimulation.', 'hitting', '2024-12-08', 'admin'),
(41, 'View each incident as an opportunity to teach problem-solving skills.', 'hitting', '2024-12-08', 'admin'),
(42, 'Avoid harsh punishments; focus on teaching and guiding instead.', 'hitting', '2024-12-08', 'admin'),
(43, 'Practice patience—your child is learning over time.', 'hitting', '2024-12-08', 'admin'),
(44, 'Maintain realistic expectations about your child’s self-control.', 'hitting', '2024-12-08', 'admin'),
(45, 'Reframe hitting as a sign that your child needs your support, not discipline.', 'hitting', '2024-12-08', 'admin'),
(46, 'Model non-aggressive ways of handling frustration in your behavior.', 'hitting', '2024-12-08', 'admin'),
(47, 'Recognize the importance of empathy and teach your child to consider others’ feelings.', 'hitting', '2024-12-08', 'admin'),
(48, 'Believe in your child’s ability to improve with consistent effort and support.', 'hitting', '2024-12-08', 'admin'),
(49, 'Focus on your long-term goal: raising a kind and emotionally intelligent person.', 'hitting', '2024-12-08', 'admin'),
(50, 'Seek professional advice if the behavior persists or worsens despite your efforts.', 'hitting', '2024-12-08', 'admin')]